import { getPageBySlug, type SitePage } from "@/lib/site-content"
import type { Locale } from "@/lib/i18n"

type PageTranslation = Pick<SitePage, "title" | "description" | "eyebrow" | "intro" | "highlights"> & {
  ctaLabel?: string
}

const translations: Record<Exclude<Locale, "ro">, Record<string, PageTranslation>> = {
  en: {
    "despre-noi": { title: "About AROFA", eyebrow: "Company", description: "We specialise in supplying and installing advanced PVC and aluminium joinery for residential and commercial projects.", intro: "Our solutions follow nZEB (Nearly Zero Energy Building) principles and help reduce energy consumption. Specialised installation details, including vapour barrier tapes, support insulation continuity and effective airtightness.", highlights: ["Certified quality: premium profiles and glazing with strong thermal performance", "Precision installation: nZEB procedures support continuous insulation and reduce thermal bridges", "Technical advice from energy performance assessment through final handover"], ctaLabel: "Learn more about AROFA" },
    "ferestre": { title: "Windows", eyebrow: "Windows", description: "A complete range of aluminium and PVC windows for residential and commercial projects.", intro: "Choose the right window system based on thermal performance, acoustic comfort, dimensions, design and budget.", highlights: ["Aluminium and PVC systems", "Solutions for renovation and new construction", "Custom colours, glazing and opening types", "Technical advice and professional installation"], ctaLabel: "Request a window quote" },
    "ferestre/aluminiu": { title: "Aluminium joinery", eyebrow: "Aluminium", description: "Slim, durable aluminium systems for windows, entrance doors and large glazed openings.", intro: "AROFA aluminium joinery combines structural stability, contemporary design and generous natural light across windows and doors.", highlights: ["Stable profiles for windows, entrance doors and large glazing", "Premium colours and finishes", "Strong resistance to intensive use and weather", "Residential and commercial configurations"], ctaLabel: "Request an aluminium quote" },
    "ferestre/pvc": { title: "PVC joinery", eyebrow: "PVC", description: "Energy-efficient PVC solutions for windows, entrance doors and sliding doors, with extensive customisation and excellent value.", intro: "AROFA PVC joinery is designed for everyday comfort, thermal insulation and a controlled budget in renovation or new-build projects.", highlights: ["High thermal and acoustic comfort", "Windows, entrance doors and sliding doors", "Foils, colours and aluminium cladding options", "Low maintenance and optimised cost"], ctaLabel: "Request a PVC quote" },
    "usi": { title: "Residential entrance doors", eyebrow: "Residential doors", description: "PVC and aluminium entrance doors combining security, insulation and design.", intro: "Configure your entrance door according to material, architectural style, security level and thermal performance.", highlights: ["Aluminium and PVC ranges", "Modern, classic and premium designs", "Custom panels, colours and glazing", "Solutions for new homes and renovation"], ctaLabel: "Request a door quote" },
    "usi-de-garaj": { title: "Residential garage doors", eyebrow: "Garage doors", description: "Insulated garage doors with comfortable operation and finishes coordinated with the façade.", intro: "AROFA garage doors combine reliable mechanics, thermal comfort and safe everyday access.", highlights: ["Insulated panels", "Manual or motorised operation", "Colours matched to the façade", "Solutions for houses, duplexes and renovation"], ctaLabel: "Request a garage door quote" },
    "usi-de-garaj-industriale": { title: "Industrial doors", eyebrow: "Industrial", description: "Industrial doors for warehouses, workshops, logistics facilities and intensive traffic.", intro: "Each solution is configured around opening size, operating frequency, safety and automation requirements.", highlights: ["Large openings and intensive traffic", "Automation and access control", "Solutions for warehouses and workshops", "Technical sizing and coordinated installation"], ctaLabel: "Discuss an industrial project" },
    "sisteme-umbrire": { title: "Shading systems", eyebrow: "Solar protection", description: "Roller shutters, solar screens and blinds for light control, privacy and thermal comfort.", intro: "Complete your windows with manual or motorised solar protection adapted to the façade and daily use.", highlights: ["Roller shutters for privacy and insulation", "Solar screens for large glazed areas", "Blinds for precise daylight control", "Manual and motorised options"], ctaLabel: "Request a shading quote" },
    "sisteme-umbrire/rulouri": { title: "Roller shutters", eyebrow: "Roller shutters", description: "Roller shutters for solar protection, privacy, thermal comfort and additional security.", intro: "Suitable for new construction and renovation, with manual or motorised operation.", highlights: ["Summer heat reduction", "Additional privacy and protection", "Manual or motorised controls", "Options for PVC and aluminium windows"], ctaLabel: "Request a roller shutter quote" },
    "sisteme-umbrire/screensolar": { title: "Solar screens", eyebrow: "Solar screens", description: "Exterior screens that filter daylight, limit overheating and maintain outward visibility.", intro: "Ideal for large windows, sliding doors, façades and terraces where solar control matters.", highlights: ["Reduced glare and overheating", "Suitable for large glazing", "Maintains a visual connection outside", "Motorised control available"], ctaLabel: "Request a solar screen quote" },
    "sisteme-umbrire/jaluzele": { title: "Blinds", eyebrow: "Blinds", description: "Blinds for accurate daylight control, adjustable privacy and a clean architectural appearance.", intro: "A flexible solution for homes, offices and contemporary façades.", highlights: ["Precise daylight adjustment", "Privacy without fully blocking light", "Finishes coordinated with the windows", "Manual and motorised options"], ctaLabel: "Request a blinds quote" },
    "servicii-de-montaj": { title: "Installation services", eyebrow: "Installation", description: "We specialise in supplying and installing advanced PVC and aluminium joinery, delivering exceptional technical solutions for residential and commercial projects.", intro: "Fully aligned with the nZEB (Nearly Zero Energy Building) standard, we integrate advanced technologies that bring energy consumption close to zero. Specialised installation details, including three-dimensional sealing with vapour barrier tapes, help eliminate thermal bridges and achieve outstanding airtightness.", highlights: ["Certified quality: We use premium profiles and glazing with excellent thermal insulation performance.", "Precision installation: Our technicians strictly follow nZEB protocols to ensure insulation continuity.", "Technical advice: We provide full support, from calculating energy performance coefficients through final handover."], ctaLabel: "Discuss installation" },
  },
  fr: {
    "despre-noi": { title: "À propos d’AROFA", eyebrow: "Entreprise", description: "Nous sommes spécialisés dans la fourniture et la pose de menuiseries PVC et aluminium pour les projets résidentiels et commerciaux.", intro: "Nos solutions suivent les principes nZEB (bâtiment à consommation d’énergie quasi nulle) et contribuent à réduire la consommation énergétique. Des détails de pose spécialisés, notamment des bandes pare-vapeur, favorisent la continuité de l’isolation et une étanchéité à l’air efficace.", highlights: ["Qualité certifiée : profils et vitrages premium aux performances thermiques élevées", "Pose de précision : protocoles nZEB pour la continuité de l’isolation et la réduction des ponts thermiques", "Conseil technique, de l’évaluation énergétique jusqu’à la réception finale"], ctaLabel: "En savoir plus sur AROFA" },
    "ferestre": { title: "Fenêtres", eyebrow: "Fenêtres", description: "Une gamme complète de fenêtres aluminium et PVC pour les projets résidentiels et commerciaux.", intro: "Choisissez le système adapté selon la performance thermique, le confort acoustique, les dimensions, le design et le budget.", highlights: ["Systèmes aluminium et PVC", "Solutions pour rénovation et construction neuve", "Couleurs, vitrages et ouvertures personnalisables", "Conseil technique et pose professionnelle"], ctaLabel: "Demander un devis fenêtres" },
    "ferestre/aluminiu": { title: "Menuiseries en aluminium", eyebrow: "Aluminium", description: "Des menuiseries en aluminium fines et durables pour fenêtres, portes d’entrée et grandes baies vitrées.", intro: "Les menuiseries en aluminium AROFA associent stabilité structurelle, design contemporain et lumière naturelle pour les fenêtres et les portes.", highlights: ["Profilés stables pour fenêtres, portes d’entrée et grands vitrages", "Couleurs et finitions premium", "Résistance aux usages intensifs et aux intempéries", "Configurations résidentielles et commerciales"], ctaLabel: "Demander un devis aluminium" },
    "ferestre/pvc": { title: "Menuiseries en PVC", eyebrow: "PVC", description: "Des menuiseries en PVC performantes et personnalisables pour fenêtres, portes d’entrée et portes coulissantes.", intro: "Les menuiseries PVC AROFA apportent confort quotidien, isolation thermique et maîtrise du budget en rénovation comme en construction neuve.", highlights: ["Très bonne isolation thermique et acoustique", "Fenêtres, portes d’entrée et portes coulissantes", "Couleurs, films et capotage aluminium", "Entretien réduit et coût optimisé"], ctaLabel: "Demander un devis PVC" },
    "usi": { title: "Portes résidentielles", eyebrow: "Portes résidentielles", description: "Portes d’entrée PVC et aluminium combinant sécurité, isolation et esthétique.", intro: "Configurez votre porte selon le matériau, le style architectural, la sécurité et la performance thermique.", highlights: ["Gammes aluminium et PVC", "Design moderne, classique ou premium", "Panneaux, couleurs et vitrages personnalisables", "Solutions pour le neuf et la rénovation"], ctaLabel: "Demander un devis portes" },
    "usi-de-garaj": { title: "Portes de garage résidentielles", eyebrow: "Portes de garage", description: "Portes isolées, faciles à utiliser et coordonnées avec la façade.", intro: "Les portes de garage AROFA associent fiabilité mécanique, confort thermique et accès sécurisé.", highlights: ["Panneaux isolants", "Commande manuelle ou motorisée", "Couleurs coordonnées à la façade", "Solutions pour maisons et rénovations"], ctaLabel: "Demander un devis garage" },
    "usi-de-garaj-industriale": { title: "Portes industrielles", eyebrow: "Industriel", description: "Portes pour halls, ateliers, entrepôts, logistique et trafic intensif.", intro: "Chaque solution est configurée selon les dimensions, la fréquence d’utilisation, la sécurité et l’automatisation.", highlights: ["Grandes ouvertures et trafic intensif", "Automatisation et contrôle d’accès", "Solutions pour entrepôts et ateliers", "Dimensionnement technique et pose coordonnée"], ctaLabel: "Étudier un projet industriel" },
    "sisteme-umbrire": { title: "Protections solaires", eyebrow: "Protection solaire", description: "Volets roulants, screens solaires et stores pour gérer lumière, intimité et confort thermique.", intro: "Complétez vos menuiseries avec une protection solaire manuelle ou motorisée adaptée à la façade.", highlights: ["Volets roulants pour intimité et isolation", "Screens solaires pour grandes surfaces vitrées", "Stores pour un réglage précis de la lumière", "Options manuelles et motorisées"], ctaLabel: "Demander un devis protection solaire" },
    "sisteme-umbrire/rulouri": { title: "Volets roulants", eyebrow: "Volets roulants", description: "Protection solaire, intimité, confort thermique et sécurité supplémentaire.", intro: "Une solution pour le neuf et la rénovation, disponible en commande manuelle ou motorisée.", highlights: ["Réduction de la surchauffe", "Intimité et protection renforcées", "Commandes manuelles ou motorisées", "Options pour fenêtres PVC et aluminium"], ctaLabel: "Demander un devis volets" },
    "sisteme-umbrire/screensolar": { title: "Screens solaires", eyebrow: "Screens solaires", description: "Screens extérieurs filtrant la lumière et limitant la surchauffe tout en conservant la vue.", intro: "Idéals pour grandes fenêtres, coulissants, façades vitrées et terrasses.", highlights: ["Réduction de l’éblouissement et de la chaleur", "Adaptés aux grands vitrages", "Vue vers l’extérieur préservée", "Motorisation disponible"], ctaLabel: "Demander un devis screens" },
    "sisteme-umbrire/jaluzele": { title: "Stores et jalousies", eyebrow: "Stores", description: "Réglage précis de la lumière, intimité modulable et esthétique architecturale soignée.", intro: "Une solution flexible pour logements, bureaux et façades contemporaines.", highlights: ["Réglage précis de la lumière", "Intimité sans obscurité totale", "Finitions coordonnées aux menuiseries", "Options manuelles et motorisées"], ctaLabel: "Demander un devis stores" },
    "servicii-de-montaj": { title: "Services de pose", eyebrow: "Pose", description: "Nous sommes spécialisés dans la fourniture et la pose de menuiseries PVC et aluminium avancées, avec des solutions techniques d’excellente qualité pour les projets résidentiels et commerciaux.", intro: "Conformément à la norme nZEB (Nearly Zero Energy Building), nous intégrons des technologies de pointe qui réduisent la consommation énergétique à un niveau proche de zéro. Des détails de pose spécialisés, notamment l’étanchéité tridimensionnelle avec des bandes pare-vapeur, contribuent à éliminer les ponts thermiques et à obtenir une excellente étanchéité à l’air.", highlights: ["Qualité certifiée : Nous utilisons exclusivement des profils et vitrages premium offrant d’excellentes performances d’isolation thermique.", "Pose de précision : Nos techniciens suivent rigoureusement les protocoles nZEB pour assurer la continuité de l’isolation.", "Conseil technique : Nous vous accompagnons du calcul des coefficients énergétiques jusqu’à la réception finale."], ctaLabel: "Discuter de la pose" },
  },
  nl: {
    "despre-noi": { title: "Over AROFA", eyebrow: "Bedrijf", description: "AROFA is gespecialiseerd in de levering en plaatsing van geavanceerd PVC- en aluminium schrijnwerk voor residentiële en commerciële projecten.", intro: "Onze oplossingen volgen de nZEB-principes (Nearly Zero Energy Building) en helpen het energieverbruik te verlagen. Gespecialiseerde plaatsingsdetails, waaronder dampremmende tapes, ondersteunen doorlopende isolatie en een goede luchtdichtheid.", highlights: ["Gecertificeerde kwaliteit: premium profielen en beglazing met sterke thermische prestaties", "Precisieplaatsing: nZEB-procedures ondersteunen doorlopende isolatie en beperken koudebruggen", "Technisch advies van beoordeling van de energieprestatie tot de uiteindelijke oplevering"], ctaLabel: "Meer over AROFA" },
    "ferestre": { title: "Ramen", eyebrow: "Ramen", description: "Een volledig gamma aluminium en PVC-ramen voor residentiële en commerciële projecten.", intro: "Kies het juiste systeem op basis van thermische prestaties, akoestisch comfort, afmetingen, ontwerp en budget.", highlights: ["Aluminium en PVC-systemen", "Oplossingen voor renovatie en nieuwbouw", "Kleuren, beglazing en openingstypes op maat", "Technisch advies en professionele plaatsing"], ctaLabel: "Offerte voor ramen aanvragen" },
    "ferestre/aluminiu": { title: "Aluminium schrijnwerk", eyebrow: "Aluminium", description: "Slank en duurzaam aluminium schrijnwerk voor ramen, voordeuren en grote glaspartijen.", intro: "Het aluminium schrijnwerk van AROFA combineert structurele stabiliteit, hedendaags design en veel natuurlijk licht voor ramen en deuren.", highlights: ["Stabiele profielen voor ramen, voordeuren en grote glaspartijen", "Premium kleuren en afwerkingen", "Bestand tegen intensief gebruik en weersinvloeden", "Residentiële en commerciële configuraties"], ctaLabel: "Offerte aluminium aanvragen" },
    "ferestre/pvc": { title: "PVC-schrijnwerk", eyebrow: "PVC", description: "Energiezuinig en veelzijdig PVC-schrijnwerk voor ramen, voordeuren en schuifdeuren.", intro: "Het PVC-schrijnwerk van AROFA biedt dagelijks comfort, goede isolatie en budgetcontrole bij renovatie en nieuwbouw.", highlights: ["Sterke thermische en akoestische isolatie", "Ramen, voordeuren en schuifdeuren", "Folies, kleuren en aluminium bekleding", "Weinig onderhoud en optimale kost"], ctaLabel: "Offerte PVC aanvragen" },
    "usi": { title: "Residentiële deuren", eyebrow: "Residentiële deuren", description: "PVC- en aluminium voordeuren die veiligheid, isolatie en design combineren.", intro: "Configureer uw deur volgens materiaal, bouwstijl, veiligheidsniveau en thermische prestaties.", highlights: ["Aluminium en PVC-gamma’s", "Moderne, klassieke en premium ontwerpen", "Panelen, kleuren en glas op maat", "Oplossingen voor nieuwbouw en renovatie"], ctaLabel: "Offerte voor deuren aanvragen" },
    "usi-de-garaj": { title: "Residentiële garagepoorten", eyebrow: "Garagepoorten", description: "Geïsoleerde garagepoorten met comfortabele bediening en afwerkingen passend bij de gevel.", intro: "AROFA garagepoorten combineren betrouwbare mechaniek, thermisch comfort en veilige toegang.", highlights: ["Geïsoleerde panelen", "Handmatige of gemotoriseerde bediening", "Kleuren afgestemd op de gevel", "Oplossingen voor woningen en renovaties"], ctaLabel: "Offerte garagepoort aanvragen" },
    "usi-de-garaj-industriale": { title: "Industriële poorten", eyebrow: "Industrieel", description: "Poorten voor hallen, werkplaatsen, magazijnen, logistiek en intensief verkeer.", intro: "Elke oplossing wordt afgestemd op afmetingen, gebruiksfrequentie, veiligheid en automatisering.", highlights: ["Grote openingen en intensief verkeer", "Automatisering en toegangscontrole", "Oplossingen voor magazijnen en werkplaatsen", "Technische dimensionering en plaatsing"], ctaLabel: "Bespreek een industrieel project" },
    "sisteme-umbrire": { title: "Zonwering", eyebrow: "Zonwering", description: "Rolluiken, zonwerende screens en jaloezieën voor lichtregeling, privacy en thermisch comfort.", intro: "Vervolledig uw ramen met manuele of gemotoriseerde zonwering afgestemd op de gevel.", highlights: ["Rolluiken voor privacy en isolatie", "Screens voor grote glaspartijen", "Jaloezieën voor precieze lichtregeling", "Manuele en gemotoriseerde opties"], ctaLabel: "Offerte zonwering aanvragen" },
    "sisteme-umbrire/rulouri": { title: "Rolluiken", eyebrow: "Rolluiken", description: "Rolluiken voor zonwering, privacy, thermisch comfort en extra veiligheid.", intro: "Geschikt voor nieuwbouw en renovatie, met manuele of gemotoriseerde bediening.", highlights: ["Minder oververhitting in de zomer", "Extra privacy en bescherming", "Manuele of gemotoriseerde bediening", "Opties voor PVC- en aluminium ramen"], ctaLabel: "Offerte rolluiken aanvragen" },
    "sisteme-umbrire/screensolar": { title: "Zonwerende screens", eyebrow: "Screens", description: "Buitenscreens die daglicht filteren, oververhitting beperken en het zicht naar buiten behouden.", intro: "Ideaal voor grote ramen, schuifdeuren, glazen gevels en terrassen.", highlights: ["Minder verblinding en oververhitting", "Geschikt voor grote glaspartijen", "Zicht naar buiten blijft behouden", "Gemotoriseerde bediening beschikbaar"], ctaLabel: "Offerte screens aanvragen" },
    "sisteme-umbrire/jaluzele": { title: "Jaloezieën", eyebrow: "Jaloezieën", description: "Nauwkeurige lichtregeling, verstelbare privacy en een strakke architecturale uitstraling.", intro: "Een flexibele oplossing voor woningen, kantoren en hedendaagse gevels.", highlights: ["Precieze regeling van daglicht", "Privacy zonder volledig te verduisteren", "Afwerkingen passend bij de ramen", "Manuele en gemotoriseerde opties"], ctaLabel: "Offerte jaloezieën aanvragen" },
    "servicii-de-montaj": { title: "Professionele plaatsing", eyebrow: "Plaatsing", description: "AROFA is gespecialiseerd in de levering en plaatsing van geavanceerd PVC- en aluminium schrijnwerk, met hoogwaardige technische oplossingen voor residentiële en commerciële projecten.", intro: "Onze oplossingen voldoen aan de nZEB-norm (Nearly Zero Energy Building) en integreren geavanceerde technologieën die het energieverbruik bijna tot nul terugbrengen. Gespecialiseerde plaatsingsdetails, waaronder driedimensionale afdichting met dampremmende tapes, helpen koudebruggen te elimineren en zorgen voor een uitstekende luchtdichtheid.", highlights: ["Gecertificeerde kwaliteit: We gebruiken uitsluitend premium profielen en beglazing met uitstekende thermische isolatiewaarden.", "Precisieplaatsing: Onze technici volgen de nZEB-protocollen strikt om de isolatie doorlopend te maken.", "Technisch advies: We bieden volledige ondersteuning, van de berekening van energieprestaties tot de uiteindelijke oplevering."], ctaLabel: "Plaatsing bespreken" },
  },
}

const genericCopy = {
  en: { eyebrow: "AROFA solution", intro: (title: string) => `${title} can be configured for the dimensions, performance level and architectural style of your project.`, description: (title: string) => `Discover ${title.toLowerCase()} from the AROFA portfolio, with technical advice and coordinated installation.`, highlights: ["Configuration tailored to your project", "Technical and commercial guidance", "Colours, finishes and operation options", "Professional measurement and installation"], ctaLabel: "Request a quote" },
  fr: { eyebrow: "Solution AROFA", intro: (title: string) => `${title} peut être configuré selon les dimensions, les performances et le style architectural de votre projet.`, description: (title: string) => `Découvrez ${title.toLowerCase()} dans la gamme AROFA, avec conseil technique et pose coordonnée.`, highlights: ["Configuration adaptée à votre projet", "Conseil technique et commercial", "Choix de couleurs, finitions et commandes", "Mesures et pose professionnelles"], ctaLabel: "Demander un devis" },
  nl: { eyebrow: "AROFA-oplossing", intro: (title: string) => `${title} kan worden afgestemd op de afmetingen, prestaties en bouwstijl van uw project.`, description: (title: string) => `Ontdek ${title.toLowerCase()} uit het AROFA-gamma, met technisch advies en gecoördineerde plaatsing.`, highlights: ["Configuratie op maat van uw project", "Technisch en commercieel advies", "Keuze uit kleuren, afwerkingen en bediening", "Professionele opmeting en plaatsing"], ctaLabel: "Offerte aanvragen" },
}

const localizedTitles: Record<Exclude<Locale, "ro">, Record<string, string>> = {
  en: { "contact": "Contact", "solicita-oferta": "Request a quote", "despre-noi": "About AROFA", "reprezentante": "Showrooms and representatives", "verande": "Verandas", "plase-insecte": "Insect screens", "montaj-profesionist": "Professional installation", "calitate-certificata": "Certified quality", "usi-culisante": "Sliding doors", "usi-culisante/aluminiu": "Aluminium sliding doors", "usi-culisante/pvc": "PVC sliding doors", "politica-confidentialitate": "Privacy policy", "termeni-conditii": "Terms and conditions", "cookies": "Cookie policy", "faq": "Frequently asked questions", "case-history": "Architectural inspiration", "durabilitate": "Durability", "cariere": "Careers", "arhitecti": "Architect area", "magazin": "AROFA shop", "avantaje": "AROFA benefits", "alte-produse": "Complementary products", "ferestre/lemn": "Wood windows and doors", "ferestre/fier": "Steel windows and doors", "usi/aluminiu": "Aluminium entrance doors", "usi/pvc": "PVC entrance doors" },
  fr: { "contact": "Contact", "solicita-oferta": "Demander un devis", "despre-noi": "À propos d’AROFA", "reprezentante": "Showrooms et représentants", "verande": "Vérandas", "plase-insecte": "Moustiquaires", "montaj-profesionist": "Pose professionnelle", "calitate-certificata": "Qualité certifiée", "usi-culisante": "Portes coulissantes", "usi-culisante/aluminiu": "Coulissants aluminium", "usi-culisante/pvc": "Coulissants PVC", "politica-confidentialitate": "Politique de confidentialité", "termeni-conditii": "Conditions générales", "cookies": "Politique relative aux cookies", "faq": "Questions fréquentes", "case-history": "Inspiration architecturale", "durabilitate": "Durabilité", "cariere": "Carrières", "arhitecti": "Espace architectes", "magazin": "Boutique AROFA", "avantaje": "Les avantages AROFA", "alte-produse": "Produits complémentaires", "ferestre/lemn": "Fenêtres et portes en bois", "ferestre/fier": "Fenêtres et portes en acier", "usi/aluminiu": "Portes d’entrée aluminium", "usi/pvc": "Portes d’entrée PVC" },
  nl: { "contact": "Contact", "solicita-oferta": "Offerte aanvragen", "despre-noi": "Over AROFA", "reprezentante": "Showrooms en vertegenwoordigers", "verande": "Veranda’s", "plase-insecte": "Insectenhorren", "montaj-profesionist": "Professionele plaatsing", "calitate-certificata": "Gecertificeerde kwaliteit", "usi-culisante": "Schuifdeuren", "usi-culisante/aluminiu": "Aluminium schuifdeuren", "usi-culisante/pvc": "PVC-schuifdeuren", "politica-confidentialitate": "Privacybeleid", "termeni-conditii": "Algemene voorwaarden", "cookies": "Cookiebeleid", "faq": "Veelgestelde vragen", "case-history": "Architecturale inspiratie", "durabilitate": "Duurzaamheid", "cariere": "Vacatures", "arhitecti": "Zone voor architecten", "magazin": "AROFA-winkel", "avantaje": "AROFA-voordelen", "alte-produse": "Aanvullende producten", "ferestre/lemn": "Houten ramen en deuren", "ferestre/fier": "Stalen ramen en deuren", "usi/aluminiu": "Aluminium voordeuren", "usi/pvc": "PVC-voordeuren" },
}

const additionalLocalizedTitles: Record<Exclude<Locale, "ro">, Record<string, string>> = {
  en: {
    "usi-de-garaj-industriale/automatizare-control-acces": "Industrial door automation and access control",
    "usi-de-garaj-industriale/dimensionare": "Industrial door sizing",
    "usi-de-garaj-industriale/montaj-service": "Industrial door installation and service",
    "sisteme-umbrire/jaluzele/manuale": "Manually operated blinds",
    "sisteme-umbrire/jaluzele/motorizate": "Motorised blinds",
    "sisteme-umbrire/screensolar/manual": "Manual solar screens",
    "sisteme-umbrire/screensolar/motorizat": "Motorised solar screens",
    "servicii-de-montaj/masuratori-planificare": "Measurements and installation planning",
    "servicii-de-montaj/ferestre-usi": "Window and door installation",
    "servicii-de-montaj/usi-garaj-industriale": "Garage and industrial door installation",
    "servicii-de-montaj/sisteme-umbrire": "Shading system installation",
    "sisteme-umbrire/rulouri/aplicate": "Surface-mounted roller shutters",
    "sisteme-umbrire/rulouri/integrate": "Integrated roller shutters",
    "sisteme-umbrire/rulouri/manuale": "Manually operated roller shutters",
    "sisteme-umbrire/rulouri/motorizate": "Motorised roller shutters",
  },
  fr: {
    "usi-de-garaj-industriale/automatizare-control-acces": "Automatisation et contrôle d’accès industriels",
    "usi-de-garaj-industriale/dimensionare": "Dimensionnement des portes industrielles",
    "usi-de-garaj-industriale/montaj-service": "Pose et service des portes industrielles",
    "sisteme-umbrire/jaluzele/manuale": "Stores à commande manuelle",
    "sisteme-umbrire/jaluzele/motorizate": "Stores motorisés",
    "sisteme-umbrire/screensolar/manual": "Screens solaires manuels",
    "sisteme-umbrire/screensolar/motorizat": "Screens solaires motorisés",
    "servicii-de-montaj/masuratori-planificare": "Mesures et planification de la pose",
    "servicii-de-montaj/ferestre-usi": "Pose de fenêtres et portes",
    "servicii-de-montaj/usi-garaj-industriale": "Pose de portes de garage et industrielles",
    "servicii-de-montaj/sisteme-umbrire": "Pose de protections solaires",
    "sisteme-umbrire/rulouri/aplicate": "Volets roulants en applique",
    "sisteme-umbrire/rulouri/integrate": "Volets roulants intégrés",
    "sisteme-umbrire/rulouri/manuale": "Volets roulants manuels",
    "sisteme-umbrire/rulouri/motorizate": "Volets roulants motorisés",
  },
  nl: {
    "usi-de-garaj-industriale/automatizare-control-acces": "Automatisering en toegangscontrole voor industriële poorten",
    "usi-de-garaj-industriale/dimensionare": "Dimensionering van industriële poorten",
    "usi-de-garaj-industriale/montaj-service": "Plaatsing en service van industriële poorten",
    "sisteme-umbrire/jaluzele/manuale": "Handmatig bediende jaloezieën",
    "sisteme-umbrire/jaluzele/motorizate": "Gemotoriseerde jaloezieën",
    "sisteme-umbrire/screensolar/manual": "Handmatige zonnescreens",
    "sisteme-umbrire/screensolar/motorizat": "Gemotoriseerde zonnescreens",
    "servicii-de-montaj/masuratori-planificare": "Opmetingen en plaatsingsplanning",
    "servicii-de-montaj/ferestre-usi": "Plaatsing van ramen en deuren",
    "servicii-de-montaj/usi-garaj-industriale": "Plaatsing van garage- en industriële poorten",
    "servicii-de-montaj/sisteme-umbrire": "Plaatsing van zonwering",
    "sisteme-umbrire/rulouri/aplicate": "Opbouwrolluiken",
    "sisteme-umbrire/rulouri/integrate": "Geïntegreerde rolluiken",
    "sisteme-umbrire/rulouri/manuale": "Handmatig bediende rolluiken",
    "sisteme-umbrire/rulouri/motorizate": "Gemotoriseerde rolluiken",
  },
}

const localizedLegalPages: Record<Exclude<Locale, "ro">, Record<string, Partial<SitePage>>> = {
  en: {
    "politica-confidentialitate": { title: "Privacy policy", eyebrow: "Legal", description: "How AROFA processes enquiry data and how you can exercise your rights.", intro: "The form collects your name, email, phone number, location and project details to answer your enquiry or take pre-contractual steps. Access is limited to the team and technical providers needed to deliver the message. Data is retained for up to 12 months when no contractual or legal duty applies and is not sold. Contact andrei.arofa@yahoo.com to request access, correction, deletion, restriction, objection or withdrawal of consent.", highlights: ["Legal basis: consent and pre-contractual steps requested by you", "Technical recipients: hosting and email delivery providers", "Typical retention: up to 12 months for enquiries without a contract", "You may also complain to the competent data protection authority"] },
    "termeni-conditii": { title: "Terms and conditions", eyebrow: "Legal", description: "General rules for using the AROFA website and its commercial information.", intro: "Website content describes product categories for information only and is not a contractual offer. Configuration, price, timing, transport, installation and warranty apply only after a quote or contract is confirmed. Images marked as inspiration are illustrative.", highlights: ["AROFA names and materials may not be reused commercially without permission", "Availability and specifications are confirmed for each project", "External services have their own terms and policies"] },
    "cookies": { title: "Cookie policy", eyebrow: "Legal", description: "Information about the necessary cookie used to remember your language.", intro: "The website uses the functional arofa_locale cookie to remember your selected language for up to 12 months. It is not used for advertising or profiling. No analytics or marketing cookies are enabled in the current version.", highlights: ["arofa_locale: functional preference, up to 12 months", "No advertising or profiling cookies", "You can remove the cookie from your browser settings"] },
  },
  fr: {
    "politica-confidentialitate": { title: "Politique de confidentialité", eyebrow: "Mentions légales", description: "Traitement des données de demande et exercice de vos droits.", intro: "Le formulaire recueille votre nom, e-mail, téléphone, localité et les détails du projet afin de répondre à votre demande ou d’effectuer des démarches précontractuelles. L’accès est limité à l’équipe et aux prestataires techniques nécessaires. Les données sont conservées au maximum 12 mois en l’absence d’obligation contractuelle ou légale et ne sont pas vendues. Écrivez à andrei.arofa@yahoo.com pour exercer vos droits d’accès, rectification, effacement, limitation, opposition ou retrait du consentement.", highlights: ["Base juridique : consentement et démarches précontractuelles demandées", "Destinataires techniques : hébergeur et service d’envoi d’e-mails", "Conservation habituelle : 12 mois maximum sans contrat", "Vous pouvez saisir l’autorité de protection des données compétente"] },
    "termeni-conditii": { title: "Conditions générales", eyebrow: "Mentions légales", description: "Règles générales d’utilisation du site et de ses informations commerciales.", intro: "Le contenu présente les catégories de produits à titre informatif et ne constitue pas une offre contractuelle. Configuration, prix, délai, transport, pose et garantie ne s’appliquent qu’après confirmation d’un devis ou contrat. Les images signalées comme inspiration sont illustratives.", highlights: ["Les noms et contenus AROFA ne peuvent être réutilisés commercialement sans accord", "Disponibilité et spécifications sont confirmées pour chaque projet", "Les services externes appliquent leurs propres conditions"] },
    "cookies": { title: "Politique relative aux cookies", eyebrow: "Mentions légales", description: "Informations sur le cookie nécessaire qui mémorise la langue.", intro: "Le site utilise le cookie fonctionnel arofa_locale pour mémoriser la langue choisie pendant 12 mois maximum. Il n’est pas utilisé à des fins publicitaires ou de profilage. Aucun cookie analytique ou marketing n’est activé actuellement.", highlights: ["arofa_locale : préférence fonctionnelle, 12 mois maximum", "Aucun cookie publicitaire ou de profilage", "Vous pouvez supprimer le cookie dans votre navigateur"] },
  },
  nl: {
    "politica-confidentialitate": { title: "Privacybeleid", eyebrow: "Juridisch", description: "Hoe AROFA aanvraaggegevens verwerkt en hoe u uw rechten uitoefent.", intro: "Het formulier verzamelt uw naam, e-mail, telefoonnummer, plaats en projectgegevens om uw aanvraag te beantwoorden of precontractuele stappen te nemen. Alleen het team en noodzakelijke technische dienstverleners krijgen toegang. Zonder contractuele of wettelijke bewaarplicht worden gegevens maximaal 12 maanden bewaard en niet verkocht. Mail naar andrei.arofa@yahoo.com voor inzage, correctie, verwijdering, beperking, bezwaar of intrekking van toestemming.", highlights: ["Rechtsgrond: toestemming en door u gevraagde precontractuele stappen", "Technische ontvangers: hosting- en e-mailleveranciers", "Gebruikelijke bewaartermijn: maximaal 12 maanden zonder contract", "U kunt een klacht indienen bij de bevoegde gegevensbeschermingsautoriteit"] },
    "termeni-conditii": { title: "Algemene voorwaarden", eyebrow: "Juridisch", description: "Algemene regels voor het gebruik van de website en commerciële informatie.", intro: "De website beschrijft productcategorieën uitsluitend ter informatie en vormt geen contractueel aanbod. Configuratie, prijs, timing, transport, plaatsing en garantie gelden pas na bevestiging van een offerte of overeenkomst. Afbeeldingen die als inspiratie zijn aangeduid, zijn illustratief.", highlights: ["AROFA-namen en materiaal mogen niet commercieel worden hergebruikt zonder toestemming", "Beschikbaarheid en specificaties worden per project bevestigd", "Externe diensten hanteren eigen voorwaarden en beleid"] },
    "cookies": { title: "Cookiebeleid", eyebrow: "Juridisch", description: "Informatie over de noodzakelijke cookie die uw taal onthoudt.", intro: "De website gebruikt de functionele cookie arofa_locale om uw taalkeuze maximaal 12 maanden te onthouden. De cookie wordt niet gebruikt voor reclame of profilering. In de huidige versie zijn geen analytische of marketingcookies actief.", highlights: ["arofa_locale: functionele voorkeur, maximaal 12 maanden", "Geen advertentie- of profileringscookies", "U kunt de cookie verwijderen via uw browserinstellingen"] },
  },
}

export function getLocalizedPage(slug: string[], locale: Locale): SitePage | undefined {
  const page = getPageBySlug(slug)
  if (!page) return page

  if (locale === "ro") {
    const romanianMaterialCopy: Record<string, Partial<SitePage>> = {
      "ferestre/aluminiu": {
        title: "T\u00e2mpl\u0103rie din aluminiu",
        description: "Solu\u021bii complete de t\u00e2mpl\u0103rie din aluminiu pentru ferestre, u\u0219i de intrare \u0219i deschideri vitrate ample.",
        intro: "T\u00e2mpl\u0103ria AROFA din aluminiu este potrivit\u0103 pentru locuin\u021be contemporane, showroom-uri \u0219i spa\u021bii comerciale unde conteaz\u0103 stabilitatea, designul suplu \u0219i lumina natural\u0103.",
        highlights: [
          "Profile stabile pentru ferestre, u\u0219i de intrare \u0219i deschideri vitrate generoase",
          "Finisaje premium, culori variate \u0219i integrare elegant\u0103 \u00een fa\u021bad\u0103",
          "Rezisten\u021b\u0103 ridicat\u0103 la utilizare intens\u0103, v\u00e2nt \u0219i varia\u021bii de temperatur\u0103",
          "Configura\u021bii pentru proiecte reziden\u021biale \u0219i comerciale",
        ],
        ctaLabel: "Solicit\u0103 ofert\u0103 pentru t\u00e2mpl\u0103rie din aluminiu",
      },
      "ferestre/pvc": {
        title: "T\u00e2mpl\u0103rie din PVC",
        description: "Solu\u021bii complete de t\u00e2mpl\u0103rie din PVC pentru ferestre, u\u0219i de intrare \u0219i u\u0219i culisante, eficiente energetic \u0219i u\u0219or de personalizat.",
        intro: "T\u00e2mpl\u0103ria AROFA din PVC ofer\u0103 confort zilnic, izola\u021bie termic\u0103 \u0219i fonic\u0103 bun\u0103 \u0219i un buget controlat, pentru locuin\u021be noi \u0219i renov\u0103ri.",
        highlights: [
          "Izola\u021bie termic\u0103 \u0219i fonic\u0103 foarte bun\u0103 pentru apartamente, case \u0219i renov\u0103ri",
          "Configura\u021bii pentru ferestre, u\u0219i de intrare \u0219i u\u0219i culisante din PVC",
          "Culori, folieri \u0219i op\u021biuni de placare cu aluminiu pentru un aspect rafinat",
          "\u00centre\u021binere simpl\u0103 \u0219i raport bun \u00eentre performan\u021b\u0103 \u0219i cost",
        ],
        ctaLabel: "Solicit\u0103 ofert\u0103 pentru t\u00e2mpl\u0103rie din PVC",
      },
    }
    return { ...page, ...romanianMaterialCopy[slug.join("/")] }
  }

  const key = slug.join("/")
  const exact = translations[locale][key] ?? localizedLegalPages[locale][key]
  if (exact) return { ...page, ...exact, seoTitle: undefined }

  const title = additionalLocalizedTitles[locale][key] ?? localizedTitles[locale][key] ?? page.title
  const generic = genericCopy[locale]
  return {
    ...page,
    seoTitle: undefined,
    title,
    eyebrow: generic.eyebrow,
    intro: generic.intro(title),
    description: generic.description(title),
    highlights: generic.highlights,
    ctaLabel: generic.ctaLabel,
  }
}
