import type { Locale } from "@/lib/i18n"

export type ProductDetails = {
  applications: string[]
  options: string[]
  choosing: string
}

const details: Record<string, Record<Locale, ProductDetails>> = {
  "usi": {
    ro: { applications: ["intrări principale pentru case și apartamente", "construcții noi și renovări", "proiecte unde ușa trebuie coordonată cu fațada"], options: ["aluminiu sau PVC, în funcție de dimensiune și buget", "panou plin, vitraj sau combinații decorative", "culori, mânere, prag și sens de deschidere"], choosing: "Alegerea pornește de la dimensiunea golului, expunerea la exterior, nivelul de utilizare și aspectul dorit. În ofertă trebuie clarificate materialul, deschiderea, accesoriile și condițiile de montaj." },
    en: { applications: ["main entrances for houses and apartments", "new-build and renovation projects", "projects where the door must match the façade"], options: ["aluminium or PVC based on size and budget", "solid panels, glazing or decorative combinations", "colours, handles, threshold and opening direction"], choosing: "Start with opening dimensions, weather exposure, usage and the desired appearance. Material, opening direction, accessories and installation conditions should be confirmed in the quote." },
    fr: { applications: ["entrées principales de maisons et appartements", "construction neuve et rénovation", "projets où la porte doit s’accorder à la façade"], options: ["aluminium ou PVC selon dimensions et budget", "panneau plein, vitrage ou combinaisons décoratives", "couleurs, poignées, seuil et sens d’ouverture"], choosing: "Le choix dépend des dimensions, de l’exposition, de l’usage et de l’esthétique. Le matériau, le sens d’ouverture, les accessoires et la pose doivent être précisés dans le devis." },
    nl: { applications: ["hoofdingangen van woningen en appartementen", "nieuwbouw en renovatie", "projecten waarbij de deur bij de gevel moet passen"], options: ["aluminium of PVC volgens afmetingen en budget", "volle panelen, glas of decoratieve combinaties", "kleuren, grepen, dorpel en draairichting"], choosing: "De keuze begint bij afmetingen, blootstelling, gebruik en gewenste uitstraling. Materiaal, draairichting, accessoires en plaatsingsvoorwaarden horen in de offerte te worden bevestigd." },
  },
  "usi/aluminiu": {
    ro: { applications: ["intrări expuse la utilizare frecventă", "case contemporane și goluri generoase", "proiecte care cer finisaje uniforme cu tâmplăria"], options: ["panouri pline sau cu inserții vitrate", "finisaje mate, texturate sau culori coordonate", "mânere, control acces și accesorii compatibile"], choosing: "Aluminiul este potrivit când stabilitatea, dimensiunea și aspectul suplu sunt prioritare. Configurația finală trebuie verificată după cotele golului și expunerea ușii." },
    en: { applications: ["entrances with frequent use", "contemporary homes and generous openings", "projects requiring finishes coordinated with windows"], options: ["solid panels or glazed inserts", "matt, textured or coordinated finishes", "handles, access control and compatible accessories"], choosing: "Aluminium suits projects prioritising stability, size and a slim appearance. The final configuration must be checked against opening dimensions and exposure." },
    fr: { applications: ["entrées fréquemment utilisées", "maisons contemporaines et grandes ouvertures", "projets aux finitions coordonnées avec les fenêtres"], options: ["panneaux pleins ou inserts vitrés", "finitions mates, texturées ou coordonnées", "poignées, contrôle d’accès et accessoires compatibles"], choosing: "L’aluminium convient lorsque stabilité, dimensions et finesse sont prioritaires. La configuration finale doit être vérifiée selon les cotes et l’exposition." },
    nl: { applications: ["intensief gebruikte ingangen", "hedendaagse woningen en ruime openingen", "projecten met afwerking passend bij de ramen"], options: ["volle panelen of glasinzetten", "matte, gestructureerde of afgestemde afwerkingen", "grepen, toegangscontrole en compatibele accessoires"], choosing: "Aluminium past wanneer stabiliteit, afmetingen en een slanke uitstraling belangrijk zijn. Controleer de configuratie aan de hand van de opening en blootstelling." },
  },
  "usi/pvc": {
    ro: { applications: ["locuințe unde izolarea și bugetul sunt prioritare", "înlocuirea ușilor existente", "intrări protejate sau cu dimensiuni uzuale"], options: ["panouri în stil modern sau clasic", "folieri și culori coordonate cu ferestrele", "vitrări, mânere și praguri adaptate utilizării"], choosing: "PVC-ul oferă o soluție practică și ușor de întreținut. Pentru alegere contează dimensiunea, expunerea, tipul panoului și modul în care ușa se racordează la pardoseală." },
    en: { applications: ["homes prioritising insulation and budget", "replacement of existing doors", "protected entrances or standard openings"], options: ["modern or classic panels", "foils and colours coordinated with windows", "glazing, handles and thresholds adapted to use"], choosing: "PVC is practical and low-maintenance. Size, exposure, panel type and the floor junction all matter when choosing the configuration." },
    fr: { applications: ["logements privilégiant isolation et budget", "remplacement de portes existantes", "entrées protégées ou dimensions courantes"], options: ["panneaux modernes ou classiques", "films et couleurs coordonnés aux fenêtres", "vitrages, poignées et seuils adaptés"], choosing: "Le PVC est pratique et facile d’entretien. Les dimensions, l’exposition, le panneau et la liaison au sol déterminent la configuration." },
    nl: { applications: ["woningen waar isolatie en budget centraal staan", "vervanging van bestaande deuren", "beschutte ingangen of standaardopeningen"], options: ["moderne of klassieke panelen", "folies en kleuren passend bij de ramen", "glas, grepen en dorpels aangepast aan gebruik"], choosing: "PVC is praktisch en onderhoudsarm. Afmetingen, blootstelling, paneeltype en aansluiting op de vloer bepalen de configuratie." },
  },
  "usi-culisante": {
    ro: { applications: ["acces către terase și grădini", "livinguri cu suprafețe vitrate mari", "separarea flexibilă a spațiilor"], options: ["aluminiu sau PVC", "una sau mai multe foi mobile", "prag, tip de mâner, vitraj și finisaj"], choosing: "Pentru o ușă culisantă contează dimensiunea totală, greutatea vitrajului, spațiul de manevră și nivelul dorit de etanșare. Tipul de sistem se alege înainte de definitivarea golului." },
    en: { applications: ["access to terraces and gardens", "living spaces with large glazing", "flexible separation of spaces"], options: ["aluminium or PVC", "one or more moving panels", "threshold, handle, glazing and finish"], choosing: "Overall size, glazing weight, operating space and sealing requirements determine the sliding system. Choose it before finalising the opening." },
    fr: { applications: ["accès aux terrasses et jardins", "séjours avec grandes surfaces vitrées", "séparation flexible des espaces"], options: ["aluminium ou PVC", "un ou plusieurs vantaux mobiles", "seuil, poignée, vitrage et finition"], choosing: "Dimensions, poids du vitrage, espace de manœuvre et étanchéité déterminent le système. Il doit être choisi avant de finaliser l’ouverture." },
    nl: { applications: ["toegang tot terras en tuin", "leefruimtes met grote glaspartijen", "flexibele scheiding van ruimtes"], options: ["aluminium of PVC", "een of meer bewegende delen", "dorpel, greep, glas en afwerking"], choosing: "Totale afmetingen, glasgewicht, bedieningsruimte en afdichting bepalen het schuifsysteem. Kies dit vóór de opening definitief wordt." },
  },
  "usi-culisante/aluminiu": {
    ro: { applications: ["deschideri ample și vitraje grele", "fațade contemporane", "terase și verande cu vedere panoramică"], options: ["configurații cu mai multe foi", "praguri și mânere adaptate proiectului", "culori și vitraje coordonate cu fațada"], choosing: "Aluminiul permite profile stabile pentru goluri mari. Dimensiunile și configurația trebuie verificate împreună cu structura, orientarea și accesul pentru montaj." },
    en: { applications: ["large openings and heavy glazing", "contemporary façades", "terraces and verandas with panoramic views"], options: ["multi-panel layouts", "project-specific thresholds and handles", "colours and glazing coordinated with the façade"], choosing: "Aluminium provides stability for large openings. Check dimensions and layout against structure, orientation and installation access." },
    fr: { applications: ["grandes ouvertures et vitrages lourds", "façades contemporaines", "terrasses et vérandas panoramiques"], options: ["configurations à plusieurs vantaux", "seuils et poignées adaptés", "couleurs et vitrages coordonnés à la façade"], choosing: "L’aluminium assure la stabilité des grandes ouvertures. Vérifiez dimensions et configuration selon structure, orientation et accès de pose." },
    nl: { applications: ["grote openingen en zwaar glas", "hedendaagse gevels", "terrassen en veranda’s met panoramisch zicht"], options: ["configuraties met meerdere delen", "projectspecifieke dorpels en grepen", "kleuren en glas passend bij de gevel"], choosing: "Aluminium biedt stabiliteit bij grote openingen. Controleer afmetingen en indeling met structuur, oriëntatie en plaatsingstoegang." },
  },
  "usi-culisante/pvc": {
    ro: { applications: ["terase rezidențiale", "renovări și goluri de dimensiuni moderate", "proiecte orientate spre izolație și buget"], options: ["configurații adaptate spațiului disponibil", "folieri și culori coordonate", "vitrări și accesorii de utilizare"], choosing: "PVC-ul este potrivit pentru multe proiecte rezidențiale. Dimensiunea foii, pragul și modul de deschidere trebuie alese astfel încât utilizarea zilnică să rămână confortabilă." },
    en: { applications: ["residential terraces", "renovations and moderate openings", "projects focused on insulation and budget"], options: ["layouts adapted to available space", "coordinated foils and colours", "glazing and operating accessories"], choosing: "PVC suits many residential projects. Panel size, threshold and opening type should support comfortable daily use." },
    fr: { applications: ["terrasses résidentielles", "rénovations et ouvertures modérées", "projets axés sur isolation et budget"], options: ["configurations adaptées à l’espace", "films et couleurs coordonnés", "vitrages et accessoires d’utilisation"], choosing: "Le PVC convient à de nombreux projets résidentiels. Dimensions, seuil et ouverture doivent préserver le confort quotidien." },
    nl: { applications: ["residentiële terrassen", "renovaties en middelgrote openingen", "projecten gericht op isolatie en budget"], options: ["indelingen aangepast aan beschikbare ruimte", "afgestemde folies en kleuren", "glas en bedieningsaccessoires"], choosing: "PVC past bij veel woonprojecten. Vleugelmaat, dorpel en openingstype moeten comfortabel dagelijks gebruik ondersteunen." },
  },
  "ferestre/aluminiu": {
    ro: { applications: ["case contemporane și vile", "fațade vitrate și deschideri mari", "showroom-uri și spații comerciale"], options: ["ferestre fixe, oscilo-batante sau speciale", "culori RAL și finisaje texturate", "geam termoizolant și feronerie adaptată"], choosing: "Aluminiul este recomandat când dimensiunile, stabilitatea și designul suplu sunt prioritare. Configurația finală se stabilește după orientare, dimensiunea golului și nivelul de izolație urmărit." },
    en: { applications: ["contemporary homes and villas", "glazed façades and large openings", "showrooms and commercial spaces"], options: ["fixed, tilt-and-turn or special windows", "RAL colours and textured finishes", "insulated glazing and adapted hardware"], choosing: "Choose aluminium when large dimensions, stability and slim design are priorities. The final configuration depends on orientation, opening size and insulation requirements." },
    fr: { applications: ["maisons contemporaines et villas", "façades vitrées et grandes ouvertures", "showrooms et espaces commerciaux"], options: ["fenêtres fixes, oscillo-battantes ou spéciales", "couleurs RAL et finitions texturées", "vitrage isolant et quincaillerie adaptée"], choosing: "L’aluminium est recommandé lorsque les grandes dimensions, la stabilité et la finesse du design sont prioritaires. La configuration dépend de l’orientation, des dimensions et de l’isolation recherchée." },
    nl: { applications: ["hedendaagse woningen en villa’s", "glazen gevels en grote openingen", "showrooms en commerciële ruimtes"], options: ["vaste, draai-kiep- of speciale ramen", "RAL-kleuren en structuurlakken", "isolerende beglazing en aangepast beslag"], choosing: "Kies aluminium wanneer grote afmetingen, stabiliteit en een slank ontwerp belangrijk zijn. De configuratie hangt af van oriëntatie, opening en gewenste isolatie." },
  },
  "ferestre/pvc": {
    ro: { applications: ["apartamente și case familiale", "renovări și înlocuiri de tâmplărie", "proiecte cu buget atent controlat"], options: ["mai multe niveluri de performanță", "folieri, culori și placare cu aluminiu", "geam termoizolant și opțiuni de siguranță"], choosing: "PVC-ul este o alegere foarte bună pentru izolație și cost optim. Contează profilul, pachetul de sticlă, feroneria și mai ales calitatea montajului." },
    en: { applications: ["apartments and family homes", "renovation and window replacement", "projects with a controlled budget"], options: ["several performance levels", "foils, colours and aluminium cladding", "insulated glazing and security options"], choosing: "PVC offers strong insulation and excellent value. Profile selection, glazing, hardware and installation quality all influence final performance." },
    fr: { applications: ["appartements et maisons familiales", "rénovation et remplacement de menuiseries", "projets au budget maîtrisé"], options: ["plusieurs niveaux de performance", "films, couleurs et capotage aluminium", "vitrage isolant et options de sécurité"], choosing: "Le PVC offre une excellente isolation pour un coût optimisé. Le profil, le vitrage, la quincaillerie et la qualité de pose déterminent la performance finale." },
    nl: { applications: ["appartementen en gezinswoningen", "renovatie en vervanging van ramen", "projecten met een beheerst budget"], options: ["verschillende prestatieniveaus", "folies, kleuren en aluminium bekleding", "isolerend glas en veiligheidsopties"], choosing: "PVC biedt sterke isolatie en een goede prijs-kwaliteitverhouding. Profiel, glas, beslag en plaatsingskwaliteit bepalen samen de prestaties." },
  },
  "usi-de-garaj": {
    ro: { applications: ["garaje atașate locuinței", "case individuale și duplexuri", "înlocuirea unei uși existente"], options: ["acționare manuală sau motorizată", "panouri termoizolante și vitraje", "culori și texturi coordonate cu fațada"], choosing: "Verificăm dimensiunile golului, spațiul disponibil sub tavan, frecvența de utilizare și nivelul de izolație necesar." },
    en: { applications: ["garages attached to the home", "detached houses and duplexes", "replacement of an existing door"], options: ["manual or motorised operation", "insulated panels and glazing", "colours and textures matched to the façade"], choosing: "We consider opening dimensions, available headroom, frequency of use and the required insulation level." },
    fr: { applications: ["garages attenants à la maison", "maisons individuelles et duplex", "remplacement d’une porte existante"], options: ["commande manuelle ou motorisée", "panneaux isolants et vitrages", "couleurs et textures coordonnées à la façade"], choosing: "Nous vérifions les dimensions, l’espace disponible sous plafond, la fréquence d’utilisation et le niveau d’isolation nécessaire." },
    nl: { applications: ["garages aan de woning", "vrijstaande woningen en duplexen", "vervanging van een bestaande poort"], options: ["handmatige of gemotoriseerde bediening", "geïsoleerde panelen en beglazing", "kleuren en texturen passend bij de gevel"], choosing: "We bekijken de afmetingen, beschikbare bovenruimte, gebruiksfrequentie en het vereiste isolatieniveau." },
  },
  "usi-de-garaj-industriale": {
    ro: { applications: ["hale și depozite", "service-uri și ateliere", "centre logistice și zone de încărcare"], options: ["automatizare și control acces", "ferestre, uși pietonale și elemente de siguranță", "configurații pentru trafic intensiv"], choosing: "Soluția se dimensionează după gol, ciclurile zilnice, viteza de operare, cerințele de siguranță și condițiile de mediu." },
    en: { applications: ["industrial halls and warehouses", "workshops and service centres", "logistics and loading areas"], options: ["automation and access control", "windows, pass doors and safety devices", "configurations for intensive traffic"], choosing: "Sizing considers the opening, daily cycles, operating speed, safety requirements and environmental conditions." },
    fr: { applications: ["halls industriels et entrepôts", "ateliers et centres de service", "zones logistiques et de chargement"], options: ["automatisation et contrôle d’accès", "fenêtres, portillons et dispositifs de sécurité", "configurations pour trafic intensif"], choosing: "Le dimensionnement tient compte de l’ouverture, des cycles quotidiens, de la vitesse, de la sécurité et des conditions ambiantes." },
    nl: { applications: ["bedrijfshallen en magazijnen", "werkplaatsen en servicecentra", "logistieke en laadruimtes"], options: ["automatisering en toegangscontrole", "ramen, loopdeuren en veiligheidsvoorzieningen", "configuraties voor intensief verkeer"], choosing: "De dimensionering houdt rekening met opening, dagelijkse cycli, snelheid, veiligheid en omgevingsomstandigheden." },
  },
  "sisteme-umbrire/rulouri": {
    ro: { applications: ["ferestre expuse la soare", "dormitoare și spații ce cer intimitate", "renovări și construcții noi"], options: ["rulouri aplicate sau integrate", "lamele și culori diferite", "acționare manuală, electrică sau automatizată"], choosing: "Tipul casetei și al acționării depinde de etapa proiectului, dimensiunea ferestrei și nivelul dorit de confort termic și intimitate." },
    en: { applications: ["sun-exposed windows", "bedrooms and privacy-sensitive spaces", "renovation and new construction"], options: ["surface-mounted or integrated shutters", "different slats and colours", "manual, electric or automated operation"], choosing: "Box type and operation depend on project stage, window dimensions and the desired level of thermal comfort and privacy." },
    fr: { applications: ["fenêtres exposées au soleil", "chambres et espaces exigeant de l’intimité", "rénovation et construction neuve"], options: ["volets en applique ou intégrés", "différentes lames et couleurs", "commande manuelle, électrique ou automatisée"], choosing: "Le coffre et la commande dépendent de l’étape du projet, des dimensions et du niveau de confort et d’intimité souhaité." },
    nl: { applications: ["ramen met sterke zonbelasting", "slaapkamers en ruimtes die privacy vragen", "renovatie en nieuwbouw"], options: ["opbouw- of geïntegreerde rolluiken", "verschillende lamellen en kleuren", "handmatige, elektrische of automatische bediening"], choosing: "Kasttype en bediening hangen af van de projectfase, raamafmetingen en gewenst thermisch comfort en privacy." },
  },
  "sisteme-umbrire/screensolar": {
    ro: { applications: ["ferestre și culisante de mari dimensiuni", "fațade sudice sau vestice", "terase, verande și spații comerciale"], options: ["țesături cu grade diferite de transparență", "ghidaje și casete adaptate proiectului", "motorizare și control pe zone"], choosing: "Alegerea țesăturii pornește de la orientare, dimensiunea vitrajului, vizibilitatea dorită și cantitatea de căldură ce trebuie respinsă." },
    en: { applications: ["large windows and sliding doors", "south- or west-facing façades", "terraces, verandas and commercial spaces"], options: ["fabrics with different openness factors", "project-specific guides and boxes", "motorisation and zoned control"], choosing: "Fabric selection depends on orientation, glazing size, desired visibility and the amount of solar heat to reject." },
    fr: { applications: ["grandes fenêtres et baies coulissantes", "façades sud ou ouest", "terrasses, vérandas et espaces commerciaux"], options: ["toiles avec différents facteurs d’ouverture", "guides et coffres adaptés", "motorisation et commande par zones"], choosing: "Le choix de la toile dépend de l’orientation, de la taille du vitrage, de la visibilité souhaitée et de la chaleur solaire à bloquer." },
    nl: { applications: ["grote ramen en schuifdeuren", "zuid- of westgerichte gevels", "terrassen, veranda’s en commerciële ruimtes"], options: ["doeken met verschillende openheidsfactoren", "geleiders en kasten op maat", "motorisering en zonebediening"], choosing: "De doekkeuze hangt af van oriëntatie, glasoppervlak, gewenst zicht en de hoeveelheid zonnewarmte die moet worden geweerd." },
  },
  "sisteme-umbrire/jaluzele": {
    ro: { applications: ["locuințe moderne", "birouri și spații comerciale", "fațade unde lumina trebuie reglată fin"], options: ["lamele în dimensiuni și culori variate", "acționare manuală sau motorizată", "integrare în scenarii de automatizare"], choosing: "Dimensiunea lamelei, ghidajele și automatizarea se aleg după expunerea la vânt, dimensiunea golului și nivelul de control dorit." },
    en: { applications: ["modern homes", "offices and commercial spaces", "façades requiring precise daylight control"], options: ["slats in multiple sizes and colours", "manual or motorised operation", "integration with automation scenarios"], choosing: "Slat size, guides and automation depend on wind exposure, opening dimensions and the desired level of control." },
    fr: { applications: ["habitations modernes", "bureaux et espaces commerciaux", "façades nécessitant un réglage précis de la lumière"], options: ["lames en plusieurs dimensions et couleurs", "commande manuelle ou motorisée", "intégration à des scénarios d’automatisation"], choosing: "La taille des lames, les guides et l’automatisation dépendent du vent, des dimensions et du niveau de contrôle souhaité." },
    nl: { applications: ["moderne woningen", "kantoren en commerciële ruimtes", "gevels met nauwkeurige daglichtregeling"], options: ["lamellen in diverse maten en kleuren", "handmatige of gemotoriseerde bediening", "integratie met automatiseringsscenario’s"], choosing: "Lamelformaat, geleiders en automatisering hangen af van windbelasting, afmetingen en gewenst bedieningsniveau." },
  },
  "servicii-de-montaj": {
    ro: { applications: ["ferestre și uși PVC sau aluminiu", "uși de garaj și sisteme industriale", "rulouri, jaluzele și screen solar"], options: ["măsurători și verificări înainte de montaj", "etanșare, fixare și reglaje finale", "predare și recomandări de întreținere"], choosing: "Montajul trebuie ales împreună cu produsul. Suportul, rosturile, etanșarea și reglajele influențează direct izolarea și durata de viață." },
    en: { applications: ["PVC and aluminium windows and doors", "garage and industrial doors", "roller shutters, blinds and solar screens"], options: ["measurements and pre-installation checks", "sealing, fixing and final adjustment", "handover and maintenance guidance"], choosing: "Installation should be specified together with the product. Substrate, joints, sealing and adjustments directly affect insulation and service life." },
    fr: { applications: ["fenêtres et portes PVC ou aluminium", "portes de garage et industrielles", "volets, stores et screens solaires"], options: ["mesures et contrôles avant pose", "étanchéité, fixation et réglages finaux", "réception et conseils d’entretien"], choosing: "La pose doit être définie avec le produit. Le support, les joints, l’étanchéité et les réglages influencent directement l’isolation et la durée de vie." },
    nl: { applications: ["PVC- en aluminium ramen en deuren", "garage- en industriële poorten", "rolluiken, jaloezieën en screens"], options: ["opmetingen en controle vooraf", "afdichting, bevestiging en eindafstelling", "oplevering en onderhoudsadvies"], choosing: "Plaatsing hoort samen met het product te worden bepaald. Ondergrond, voegen, afdichting en afstelling beïnvloeden isolatie en levensduur rechtstreeks." },
  },
}

export function getProductDetails(slug: string[], locale: Locale) {
  const key = slug.join("/")
  const exact = details[key]?.[locale]
  if (exact) return exact

  const family = [
    "usi-de-garaj-industriale",
    "sisteme-umbrire/jaluzele",
    "sisteme-umbrire/screensolar",
    "sisteme-umbrire/rulouri",
    "servicii-de-montaj",
    "usi-culisante/aluminiu",
    "usi-culisante/pvc",
    "usi/aluminiu",
    "usi/pvc",
  ].find((path) => key.startsWith(`${path}/`))

  return family ? details[family]?.[locale] : undefined
}
